### ISSUE TITLE
Need to update your README

### ISSUE THREAD

**Issue by thomaslsimpson** [Avocarrot/openrtb#41]
The README seems to have outdated information about how to load and use your module. The newer version seems to be using a factory and needs a different construction process?

**Comment by giorgosera** [comment]
Thanks for pointing this out @thomaslsimpson. Development of the module is a bit slower these days but this is noted.

**Comment by giorgosera** [comment]
This has been fixed at https://github.com/Avocarrot/openrtb/pull/45

Thanks for the contribution :)

**Comment by thomaslsimpson** [comment]
Happy to be ever so slightly helpful.
