### ISSUE TITLE
Bid Request Validation

### ISSUE THREAD

**Issue by mircea-pop** [Avocarrot/openrtb#42]
would be really helpful to also have a bid request validation. As far as I can see, there is only a bid response validation. 
This would be useful in tests, as in production would take to long

**Comment by giorgosera** [comment]
Very good idea @mircea-pop . Development is a bit slower these days due to other priorities. Feel free to submit PR with your contributions. Hopefully, we'll find some time to implement your suggestion before that though:)

**Comment by giorgosera** [comment]
FYI we just shipped this (#48).
