### ISSUE TITLE
Needs steps wise suggestion to execute application

### ISSUE THREAD

**Issue by rupak1989** [Avocarrot/openrtb#57]
Dear Sir,

Thanks for sharing your experience with open RTB,

I hope my question may be wrong , but i am not able to run application after taking clone and installing as per required package .But i am not able to execute application.

Please  suggest, how to run this application ?

Thanks
Rupak

**Comment by giorgosera** [comment]
Hey Rupak. What do you mean by run application? 

You can check the README for instructions on how to use this library.

Note: This is *not* a library to run an RTB exchange or DSP. It's simply a library that facilitates the serialization of raw JS objects to valid OpenRTB constructs. It's essentially a helper for apps that implement the OpenRTB bidding protocol.
